config/routes.rb
Rails.application.routes.draw do
   root to:  'resturants#index'
  # get "/resturant/:id", to: "resturant#show"

   resources :resturants
   resources :orders
   resources :food_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	belongs_to :order
	belongs_to :resturant
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :resturant
	has_many :food_items, dependent: :destroy

	accepts_nested_attributes_for :food_items
end

app/models/resturant.rb
class Resturant < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :food_items
	has_one :orders
end

app/models/user.rb
class User < ApplicationRecord
	has_and_belongs_to_many :resturants
	has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
	# before_action :signed_in_user, only: [:index, :destroy, :create, :new]

  def index
    binding.pry
    resturant = Resturant.find_by(id: params[:resturant_id])
    @food_items = resturant.food_items
  end

  def show
     resturant = Resturant.find_by(id: params[:resturant_id])
    @food_items = resturant.food_items
    @order = Order.new
  end


  def new
    resturant = Resturant.find_by(id: params[:resturant_id])
    @food_items = resturant.food_items.new
  end

  def destroy
    FoodItem.find(params[:id]).destroy
    flash[:success] = "Food Item deleted."
    redirect_to food_items_url
  end

  def create
    @food_item = FoodItem.new(food_item_params)

    if @food_item.save
      flash[:success] = "Food Item \"#{@food_item.title}\" added"
      redirect_to food_items_path
    else
      render 'new'
    end
  end

  private
    def food_item_params
      params.require(:food_item).permit(:title, :description, :picture_url, :price, :active)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def new
  	@order = Order.new
  end

  def create
    binding.pry
    @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to user_path(@current_user)
    else
      # Try to redirect him back to the Add Order page if we have a food_item_id
      if @order.food_item_id != nil
        @food_item = FoodItem.find(@order.food_item_id)
        render :template => "food_items/show"
      else
        redirect_to user_path(@current_user)
      end
    end
  end


  def destroy
    if @order.paid || @order.delivered
      flash[:error] = "You cannot delete an order you've paid for!"
    else
      @order.destroy
    end
    route_selector
  end

  def cancellation
    @order = get_pending_order
    @food_item = @order == nil ? nil : FoodItem.find(@order.food_item_id)
  end


  private

    def order_params
      params.require(:order).permit(
        :name, :address, :title, :price, :destription, :quantity, :resturant_food_ids
      )
    end

end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController

	def index
		@resturants = Resturant.all
	end

  def show
    @resturant = Resturant.find(params[:id])
  end

  def new
    @resturant = Resturant.new
  end

  def create
    @resturant = Resturant.new(title: "...", body: "...")

    if @resturant.save
      redirect_to @resturant
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/views/food_items/index.html.erb
<div>
<h3>Food Items</h3>
  <ul>
  <% @food_items.each do |food| %>
      <li>
        <h6>Title:<%= food.title -%></h6>
        <h6>Price:<%= food.price -%></h6>
        <h6>Description: <%= food.destription -%></h6>
        <h6>Quantity:  <%= text_field_tag "quantity" %></h6>
        <%= check_box_tag 'resturant_food_ids[]', food.id %>
      </li>
  <% end %>
</ul>
</div>

app/views/food_items/new.html.erb
<div>

<h3>Food Items</h3>
  <ul>
  <%= form_for(@food_items) do |food| %>
      <li>
        <h6>Title:<%= food.title -%></h6>
        <h6>Price:<%= food.price -%></h6>
        <h6>Description: <%= food.destription -%></h6>
        <h6>Quantity:  <%= text_field_tag "quantity" %></h6>
        <%= check_box_tag 'resturant_food_ids[]', food.id %>
      </li>
  <% end %>
</ul>
<div class="actions">
    <%= f.submit %>
  </div>
</div>

app/views/food_items/show.html.erb
<div>

<h3>Food Items</h3>
  <ul>
  <%= form_for(@order) do |food| %>
      <li>
        <h6>Title:<%= food.title -%></h6>
        <h6>Price:<%= food.price -%></h6>
        <h6>Description: <%= food.destription -%></h6>
        <h6>Quantity:  <%= text_field_tag "quantity" %></h6>
        <%= check_box_tag 'resturant_food_ids[]', food.id %>
      </li>
  <% end %>
</ul>
<div class="actions">
    <%= f.submit %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineFoodOrder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>
<%= link_to 'Back', orders_path %>

app/views/resturants/index.html.erb
<h1>Resturants</h1>
<ul>
  <% @resturants.each do |resturant| %>
    <li>
      <h3>Resturant name:<%= link_to resturant.name, resturant %></h3>
    </li>
  <% end %>
</ul>

app/views/resturants/show.html.erb
<div class="row">
	<div class="col-md-8">
		<div class="resturant-info">
			<h2>Name: <%= @resturant.name %></h2>
	      <h4>Location: <%= @resturant.location %></h4>
	  </div>
  </div>
</div>

		<div>
			<%= link_to "Check Food Items", food_item_path(resturant_id: @resturant), class: "btn btn-custom" %>
		</div>
		</div>	

<%= link_to "Back", root_path, class: "btn btn-custom"%>

<%# if user_signed_in? %>

<%# if @resturant.user_id == current_user.id %>

<%#= link_to "Edit", edit_resturant_path(@resturant), class: "btn btn-custom" %>
<%#= link_to "Delete", resturant_path(@resturant), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-custom"%>

<%# end %>
<%# end %>
</div>